on:
  push:
    branches: ["main"]

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
      - name: Install xvfb for unit tests
        run: sudo apt install xvfb
      - run: ./gradlew build
