on:
  push:
    branches: ["main"]

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
      - name: Install xvfb for unit tests
        run: sudo apt install xvfb
      - name: Setup xvfb for screen 0 &
        run: Xvfb :1 -screen 0 1600x1200x16
      - run: ./gradlew build
        env:
          DISPLAY: :1
      - name: Tear down xvfb
        run: killall Xvfb
