on:
  push:
    branches: ["main"]

name: build

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
      - name: Install xvfb for headless unit tests
        run: sudo apt install xvfb
      - run: xvfb-run ./gradlew build
      - name: Archive test images
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test images
          path: build/test-results/test/binary/testimg
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
